name: NixOS Rebuild

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rebuild:
    runs-on: nixos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Nix Environment
      run: |
        nix-env -iA nixpkgs.nixos-rebuild

    - name: Build NixOS configuration for desktop
      run: |
        sudo nixos-rebuild switch --flake .#desktop
